#!/usr/bin/env python3
"""Headless PX4 worker pool with pluggable simulator backends."""

from __future__ import annotations

import json
import os
import queue
import shutil
import signal
import subprocess
import sys
import threading
import time
from collections import deque
from concurrent.futures import Future, ThreadPoolExecutor
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Optional

from controller_profiles import (
    ControllerProfile,
    param_names,
    param_spec_map,
    write_param_file as write_controller_param_file,
)
from runtime_cleanup import cleanup_runtime_slots
from simulator_backend import (
    DEFAULT_GZ_VEHICLE,
    DEFAULT_GZ_WORLD,
    build_simulator_launch_spec,
    normalize_simulator_name,
    prepare_rootfs_simulator_assets,
    simulator_state_fields,
    wait_for_simulator_ready,
)


def atomic_write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    tmp.replace(path)


def write_param_file(path: Path, params: Dict[str, float], profile: ControllerProfile) -> None:
    write_controller_param_file(
        path,
        profile,
        params,
        header="Autogenerated by parallel_pool.py",
    )


def archive_eval_trace(results_dir: Path, eval_index: int, payload: dict, result_json: Optional[Path] = None) -> None:
    raw_log = str(payload.get("tracking_log", "")).strip()
    if not raw_log:
        return

    src = Path(raw_log)
    if not src.exists():
        return

    dst = results_dir / "eval_traces" / f"eval_{eval_index:05d}.csv"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    payload["tracking_log_archive"] = str(dst)

    if result_json is not None and result_json.exists():
        try:
            on_disk = json.loads(result_json.read_text(encoding="utf-8"))
        except Exception:
            on_disk = {}
        on_disk["tracking_log_archive"] = str(dst)
        atomic_write_json(result_json, on_disk)


def archive_identification_log(results_dir: Path, eval_index: int, payload: dict, result_json: Optional[Path] = None) -> None:
    raw_log = str(payload.get("identification_log", "")).strip()
    if not raw_log:
        return

    src = Path(raw_log)
    if not src.exists():
        return

    dst = results_dir / "identification_traces" / f"eval_{eval_index:05d}.csv"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    payload["identification_log_archive"] = str(dst)

    if result_json is not None and result_json.exists():
        try:
            on_disk = json.loads(result_json.read_text(encoding="utf-8"))
        except Exception:
            on_disk = {}
        on_disk["identification_log_archive"] = str(dst)
        atomic_write_json(result_json, on_disk)


def archive_gazebo_truth_log(
    results_dir: Path,
    eval_index: int,
    payload: dict,
    raw_log_dir: Path,
    *,
    result_json: Optional[Path] = None,
) -> None:
    if not raw_log_dir.exists():
        return

    candidates = [
        path for path in raw_log_dir.glob("*.csv")
        if path.is_file()
    ]
    if not candidates:
        return

    src = max(candidates, key=lambda path: path.stat().st_mtime)
    dst = results_dir / "gazebo_truth_traces" / f"eval_{eval_index:05d}.csv"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    payload["gazebo_truth_log_archive"] = str(dst)

    if result_json is not None and result_json.exists():
        try:
            on_disk = json.loads(result_json.read_text(encoding="utf-8"))
        except Exception:
            on_disk = {}
        on_disk["gazebo_truth_log_archive"] = str(dst)
        atomic_write_json(result_json, on_disk)


def copy_tree_contents(src: Path, dst: Path, ignore: Optional[callable] = None) -> None:
    if not src.exists():
        return
    for item in src.iterdir():
        if ignore is not None and item.name in ignore(src, [item.name]):
            continue
        target = dst / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True, ignore=ignore)
        elif item.is_symlink():
            if target.exists() or target.is_symlink():
                target.unlink()
            target.symlink_to(item.resolve())
        else:
            shutil.copy2(item, target)


class Px4CtlLite:
    def __init__(self, rootfs: Path, bin_dir: Path, instance_id: int):
        self.rootfs = rootfs
        self.bin_dir = bin_dir
        self.instance_id = instance_id

    def command(self, command_line: str, timeout_s: float = 6.0) -> str:
        parts = command_line.split()
        if not parts:
            return ""
        exe = self.bin_dir / f"px4-{parts[0]}"
        proc = subprocess.run(
            [str(exe), "--instance", str(self.instance_id), *parts[1:]],
            cwd=str(self.rootfs),
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode != 0:
            raise RuntimeError(out.strip() or f"{exe.name} failed")
        return out


@dataclass
class EvalTask:
    eval_index: int
    iteration: int
    phase: str
    candidate: str
    params: Dict[str, float]


@dataclass
class WorkerState:
    worker_id: int
    instance_id: int
    tcp_port: int
    state: str = "idle"
    current_eval: int = -1
    current_iteration: int = -1
    phase: str = ""
    candidate: str = ""
    started_at: float = 0.0
    last_duration_s: float = 0.0
    completed: int = 0
    failures: int = 0
    restart_count: int = 0
    error: str = ""
    trace_relpath: str = ""


class SitlWorker:
    def __init__(
        self,
        worker_id: int,
        instance_id: int,
        tcp_port: int,
        repo_root: Path,
        build_dir: Path,
        base_rootfs: Path,
        pool_dir: Path,
        results_dir: Path,
        eval_script: Path,
        profile: ControllerProfile,
        sim_speed_factor: float,
        max_evals_per_boot: int,
        simulator: str,
        simulator_vehicle: str,
        simulator_world: str,
    ) -> None:
        self.worker_id = worker_id
        self.instance_id = instance_id
        self.tcp_port = tcp_port
        self.repo_root = repo_root
        self.build_dir = build_dir
        self.base_rootfs = base_rootfs
        self.pool_dir = pool_dir
        self.results_dir = results_dir
        self.eval_script = eval_script
        self.profile = profile
        self.sim_speed_factor = max(0.1, float(sim_speed_factor))
        self.max_evals_per_boot = max(1, int(max_evals_per_boot))
        self.simulator = normalize_simulator_name(simulator)
        self.simulator_vehicle = str(simulator_vehicle or DEFAULT_GZ_VEHICLE)
        self.simulator_world = str(simulator_world or DEFAULT_GZ_WORLD)

        self.rootfs = self.pool_dir / f"worker_{worker_id:02d}"
        self.params_file = self.rootfs / "parameters" / self.profile.param_file_name
        self.live_trace_json = self.results_dir / "live_traces" / f"worker_{worker_id:02d}.json"
        self.sim_log = self.results_dir / "worker_logs" / f"worker_{worker_id:02d}_{self.simulator}.log"
        self.px4_log = self.results_dir / "worker_logs" / f"worker_{worker_id:02d}_px4.log"

        self.eval_proc: Optional[subprocess.Popen] = None
        self.sim_proc: Optional[subprocess.Popen] = None
        self.px4_proc: Optional[subprocess.Popen] = None
        self._fresh_boot = False
        self._evals_since_restart = 0
        self._lock = threading.Lock()
        self._cleanup_hints: list[str] = [str(self.rootfs)]

    def trace_relpath(self) -> str:
        return str(self.live_trace_json.relative_to(self.results_dir.parent))

    def prepare_filesystem(self) -> None:
        shutil.rmtree(self.rootfs, ignore_errors=True)
        self.rootfs.mkdir(parents=True, exist_ok=True)
        (self.rootfs / "log").mkdir(parents=True, exist_ok=True)
        (self.rootfs / "eeprom").mkdir(parents=True, exist_ok=True)
        (self.rootfs / "parameters").mkdir(parents=True, exist_ok=True)
        (self.rootfs / "trajectories").mkdir(parents=True, exist_ok=True)
        (self.rootfs / "tracking_logs").mkdir(parents=True, exist_ok=True)

        etc_link = self.rootfs / "etc"
        if etc_link.exists() or etc_link.is_symlink():
            etc_link.unlink()
        etc_link.symlink_to((self.build_dir / "etc").resolve())

        prepare_rootfs_simulator_assets(
            self.repo_root,
            self.build_dir,
            self.base_rootfs,
            self.rootfs,
            self.simulator,
        )

        test_data = self.rootfs / "test_data"
        if test_data.exists() or test_data.is_symlink():
            test_data.unlink()
        if (self.repo_root / "test_data").exists():
            test_data.symlink_to((self.repo_root / "test_data").resolve())

        if (self.base_rootfs / "dataman").exists():
            shutil.copy2(self.base_rootfs / "dataman", self.rootfs / "dataman")

        if (self.base_rootfs / "parameters").exists():
            copy_tree_contents(self.base_rootfs / "parameters", self.rootfs / "parameters")

        if (self.base_rootfs / "trajectories").exists():
            shutil.copytree(
                self.base_rootfs / "trajectories",
                self.rootfs / "trajectories",
                dirs_exist_ok=True,
                ignore=shutil.ignore_patterns("tracking_logs"),
            )

        if (self.base_rootfs / "tracking_logs").exists():
            shutil.copytree(
                self.base_rootfs / "tracking_logs",
                self.rootfs / "tracking_logs",
                dirs_exist_ok=True,
            )

        for stale in (
            self.rootfs / "parameters.bson",
            self.rootfs / "parameters_backup.bson",
            self.rootfs / "param_import_fail.bson",
        ):
            stale.unlink(missing_ok=True)

    def _terminate_proc(self, proc: Optional[subprocess.Popen], timeout_s: float = 8.0) -> None:
        if proc is None or proc.poll() is not None:
            return
        try:
            os.killpg(proc.pid, signal.SIGTERM)
            proc.wait(timeout=timeout_s)
        except Exception:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
                proc.wait(timeout=3.0)
            except Exception:
                pass

    def stop(self) -> None:
        with self._lock:
            self._terminate_proc(self.eval_proc, timeout_s=4.0)
            self._terminate_proc(self.px4_proc)
            self._terminate_proc(self.sim_proc)
            self.eval_proc = None
            self.px4_proc = None
            self.sim_proc = None
            self._fresh_boot = False
        cleanup_runtime_slots(
            self.repo_root,
            instance_ids=[self.instance_id],
            ports=[self.tcp_port],
            process_hints=self._cleanup_hints,
        )

    def _wait_px4_ready(self, timeout_s: float = 50.0) -> None:
        ctl = Px4CtlLite(self.rootfs, self.build_dir / "bin", self.instance_id)
        t0 = time.time()
        last_error = ""
        ready_hits = 0
        while time.time() - t0 < timeout_s:
            if self.px4_proc is not None and self.px4_proc.poll() is not None:
                raise RuntimeError(f"PX4 exited early with code {self.px4_proc.returncode}")
            if self.sim_proc is not None and self.sim_proc.poll() is not None:
                raise RuntimeError(f"{self.simulator} exited early with code {self.sim_proc.returncode}")
            try:
                out = ctl.command("commander status", timeout_s=4.0)
                if "navigation mode" in out or "armed:" in out:
                    ready_hits += 1
                    if ready_hits >= 2:
                        time.sleep(0.8)
                        return
                else:
                    ready_hits = 0
            except Exception as exc:
                ready_hits = 0
                last_error = str(exc)
            time.sleep(0.6)
        raise RuntimeError(f"PX4 not ready in {timeout_s:.1f}s: {last_error}")

    def start(self) -> None:
        last_error: Optional[Exception] = None
        for _attempt in range(3):
            with self._lock:
                cleanup_runtime_slots(
                    self.repo_root,
                    instance_ids=[self.instance_id],
                    ports=[self.tcp_port],
                    process_hints=self._cleanup_hints,
                )
                self.prepare_filesystem()
                self.results_dir.joinpath("worker_logs").mkdir(parents=True, exist_ok=True)
                self.results_dir.joinpath("live_traces").mkdir(parents=True, exist_ok=True)

                sim_log = self.sim_log.open("w", encoding="utf-8")
                px4_log = self.px4_log.open("w", encoding="utf-8")

                try:
                    sim_spec = build_simulator_launch_spec(
                        repo_root=self.repo_root,
                        build_dir=self.build_dir,
                        base_rootfs=self.base_rootfs,
                        rootfs=self.rootfs,
                        simulator=self.simulator,
                        instance_id=self.instance_id,
                        tcp_port=self.tcp_port,
                        sim_speed_factor=self.sim_speed_factor,
                        headless=True,
                        slot_name=f"worker_{self.worker_id:02d}",
                        simulator_vehicle=self.simulator_vehicle,
                        simulator_world=self.simulator_world,
                    )
                    self._cleanup_hints = list(sim_spec.cleanup_hints)
                    self.sim_proc = subprocess.Popen(
                        sim_spec.command,
                        cwd=str(self.rootfs),
                        stdout=sim_log,
                        stderr=subprocess.STDOUT,
                        start_new_session=True,
                        env=sim_spec.environment,
                    )
                    wait_for_simulator_ready(sim_spec, timeout_s=30.0)

                    px4_cmd = [
                        str(self.build_dir / "bin" / "px4"),
                        "-i", str(self.instance_id),
                        "-d", str(self.build_dir / "etc"),
                    ]
                    px4_env = os.environ.copy()
                    for key, value in sim_spec.px4_environment.items():
                        if value == "":
                            continue
                        px4_env[key] = str(value)
                    self.px4_proc = subprocess.Popen(
                        px4_cmd,
                        cwd=str(self.rootfs),
                        stdout=px4_log,
                        stderr=subprocess.STDOUT,
                        start_new_session=True,
                        env=px4_env,
                    )
                finally:
                    sim_log.close()
                    px4_log.close()

            try:
                self._wait_px4_ready()
                self._fresh_boot = True
                self._evals_since_restart = 0
                return
            except Exception as exc:
                last_error = exc
                self.stop()
                time.sleep(0.75)

        raise RuntimeError(f"Worker {self.worker_id} failed to start after retries: {last_error}")

    def restart(self, reason: str = "") -> None:
        self.stop()
        self.live_trace_json.unlink(missing_ok=True)
        self.start()

    def is_alive(self) -> bool:
        return (
            self.px4_proc is not None
            and self.px4_proc.poll() is None
            and self.sim_proc is not None
            and self.sim_proc.poll() is None
        )

    def ensure_running(self) -> None:
        if not self.is_alive():
            self.restart("process_not_alive")

    def _fail_result(self, task: EvalTask, fail_penalty: float, error_text: str, duration_s: float) -> dict:
        return {
            "fitness": float(fail_penalty),
            "track_rmse": float(fail_penalty),
            "energy_term": 0.0,
            "tracking_log": "",
            "tracking_log_archive": "",
            "params_file": str(self.params_file),
            "traj_id": -1,
            "eval_id": task.eval_index,
            "failed": True,
            "stderr": error_text[:700],
            "worker_id": self.worker_id,
            "duration_s": duration_s,
        }

    def run_eval(
        self,
        task: EvalTask,
        eval_args: dict,
        eval_timeout_s: float,
        fail_penalty: float,
    ) -> dict:
        overall_started_at = time.time()
        overall_deadline = overall_started_at + max(30.0, float(eval_timeout_s) * 1.20)

        def remaining_budget_s() -> float:
            return max(0.0, overall_deadline - time.time())

        def fail_now(error_text: str) -> dict:
            return self._fail_result(
                task,
                fail_penalty,
                error_text,
                time.time() - overall_started_at,
            )

        self.ensure_running()
        if (not self._fresh_boot) and self._evals_since_restart >= self.max_evals_per_boot:
            self.restart("periodic_eval_reset")

        self._fresh_boot = False

        last_error = ""
        for attempt in range(2):
            if remaining_budget_s() <= 0.0:
                return fail_now(
                    f"eval exceeded overall budget {overall_deadline - overall_started_at:.1f}s before attempt {attempt + 1}"
                )
            write_param_file(self.params_file, task.params, self.profile)
            result_json = self.results_dir / f"eval_{task.eval_index:05d}.json"
            result_json.unlink(missing_ok=True)
            cmd = [
                sys.executable,
                str(self.eval_script),
                "--rootfs", str(self.rootfs),
                "--params-file", str(self.params_file),
                "--controller", self.profile.name,
                "--traj-id", str(eval_args["traj_id"]),
                "--takeoff-alt", str(eval_args["takeoff_alt"]),
                "--trajectory-timeout", str(eval_args["trajectory_timeout"]),
                "--takeoff-timeout", str(eval_args["takeoff_timeout"]),
                "--w-track", str(eval_args["w_track"]),
                "--w-energy", str(eval_args["w_energy"]),
                "--landing-mode", str(eval_args.get("landing_mode", "land")),
                "--trace-window", str(eval_args.get("trace_window", "offboard")),
                "--engagement-dwell-s", str(eval_args.get("engagement_dwell_s", 2.0)),
                "--mission-mode", str(eval_args.get("mission_mode", "trajectory")),
                "--ident-profile", str(eval_args.get("ident_profile", "hover_thrust")),
                "--shell-endpoint", "unused",
                "--telemetry-endpoint", "unused",
                "--result-json", str(result_json),
                "--live-trace-json", str(self.live_trace_json),
                "--eval-id", str(task.eval_index),
                "--worker-id", str(self.worker_id),
                "--instance-id", str(self.instance_id),
            ]
            for name, value in sorted(eval_args.get("fixed_params", {}).items()):
                cmd.extend(["--fixed-param", f"{name}={value}"])
            if str(eval_args.get("base_param_file", "")).strip():
                cmd.extend(["--base-param-file", str(eval_args["base_param_file"])])
            try:
                attempt_timeout_s = min(float(eval_timeout_s), max(5.0, remaining_budget_s()))
                self.eval_proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    start_new_session=True,
                )
                stdout, stderr = self.eval_proc.communicate(timeout=attempt_timeout_s)
                returncode = self.eval_proc.returncode
                duration_s = time.time() - overall_started_at
            except subprocess.TimeoutExpired as exc:
                duration_s = time.time() - overall_started_at
                stderr = (exc.stderr or "").strip() if isinstance(exc.stderr, str) else ""
                self._terminate_proc(self.eval_proc, timeout_s=2.0)
                self.eval_proc = None
                last_error = (
                    f"eval timeout after {attempt_timeout_s:.1f}s on attempt {attempt + 1}; {stderr}"
                ).strip()
                if remaining_budget_s() <= 5.0:
                    return fail_now(
                        f"{last_error}; overall budget exhausted after {duration_s:.1f}s"
                    )
                self.restart("eval_timeout")
                continue
            finally:
                self.eval_proc = None

            if returncode == 0:
                if result_json.exists():
                    payload = json.loads(result_json.read_text(encoding="utf-8"))
                else:
                    payload = json.loads(stdout.strip().splitlines()[-1])
                archive_eval_trace(self.results_dir, task.eval_index, payload, result_json=result_json)
                archive_identification_log(self.results_dir, task.eval_index, payload, result_json=result_json)
                archive_gazebo_truth_log(
                    self.results_dir,
                    task.eval_index,
                    payload,
                    self.rootfs / "sysid_truth_logs",
                    result_json=result_json,
                )
                payload["failed"] = False
                payload["stderr"] = ""
                payload["worker_id"] = self.worker_id
                payload["duration_s"] = duration_s
                self._evals_since_restart += 1
                return payload

            last_error = (stderr or stdout or "").strip()
            if remaining_budget_s() <= 5.0:
                return fail_now(
                    f"{last_error or 'evaluation failed'}; overall budget exhausted after {duration_s:.1f}s"
                )
            self.restart(f"eval_failed_attempt_{attempt}")

        return fail_now(last_error or "evaluation failed")


class WorkerPool:
    def __init__(
        self,
        repo_root: Path,
        build_dir: Path,
        base_rootfs: Path,
        results_dir: Path,
        pool_dir: Path,
        worker_count: int,
        instance_base: int,
        tcp_port_base: int,
        total_expected_evals: int,
        profile: ControllerProfile,
        sim_speed_factor: float,
        max_evals_per_boot: int,
        simulator: str,
        simulator_vehicle: str,
        simulator_world: str,
    ) -> None:
        self.repo_root = repo_root
        self.build_dir = build_dir
        self.base_rootfs = base_rootfs
        self.results_dir = results_dir
        self.pool_dir = pool_dir
        self.worker_count = worker_count
        self.total_expected_evals = total_expected_evals
        self.profile = profile
        self.simulator = normalize_simulator_name(simulator)
        self.simulator_vehicle = str(simulator_vehicle or DEFAULT_GZ_VEHICLE)
        self.simulator_world = str(simulator_world or DEFAULT_GZ_WORLD)
        self.status_file = self.results_dir / "pool_status.json"
        self.started_at = time.time()
        self.executor = ThreadPoolExecutor(max_workers=worker_count, thread_name_prefix="ctrl-worker")
        self.available_workers: queue.Queue[SitlWorker] = queue.Queue()
        self.status_lock = threading.Lock()
        self.total_eval_duration_s = 0.0
        self.completed_evals = 0
        self.failed_evals = 0
        hist_len = max(16, worker_count * 16)
        self.duration_history_s = deque(maxlen=hist_len)
        self.completion_times_s = deque(maxlen=hist_len)
        self._stop_event = threading.Event()
        self._status_thread: Optional[threading.Thread] = None

        eval_script = self.repo_root / "Tools" / "optimization" / "px4_eval.py"
        self.workers = []
        self.worker_states: Dict[int, WorkerState] = {}
        for worker_id in range(worker_count):
            instance_id = instance_base + worker_id
            tcp_port = tcp_port_base + instance_id
            worker = SitlWorker(
                worker_id=worker_id,
                instance_id=instance_id,
                tcp_port=tcp_port,
                repo_root=repo_root,
                build_dir=build_dir,
                base_rootfs=base_rootfs,
                pool_dir=pool_dir,
                results_dir=results_dir,
                eval_script=eval_script,
                profile=profile,
                sim_speed_factor=sim_speed_factor,
                max_evals_per_boot=max_evals_per_boot,
                simulator=self.simulator,
                simulator_vehicle=self.simulator_vehicle,
                simulator_world=self.simulator_world,
            )
            self.workers.append(worker)
            self.worker_states[worker_id] = WorkerState(
                worker_id=worker_id,
                instance_id=instance_id,
                tcp_port=tcp_port,
                trace_relpath=worker.trace_relpath(),
            )

    def _set_worker_state(self, worker: SitlWorker, **kwargs: object) -> None:
        with self.status_lock:
            state = self.worker_states[worker.worker_id]
            for key, value in kwargs.items():
                setattr(state, key, value)
            self._write_status_locked()

    def _record_completion_locked(self, duration_s: float, failed: bool) -> None:
        self.completed_evals += 1
        self.total_eval_duration_s += max(0.0, duration_s)
        self.duration_history_s.append(max(0.0, duration_s))
        self.completion_times_s.append(time.time())
        if failed:
            self.failed_evals += 1

    def _write_status_locked(self) -> None:
        elapsed_s = max(1e-9, time.time() - self.started_at)
        busy = sum(1 for st in self.worker_states.values() if st.state == "running")
        if self.duration_history_s:
            avg_eval_s = sum(self.duration_history_s) / len(self.duration_history_s)
        elif self.completed_evals > 0:
            avg_eval_s = self.total_eval_duration_s / self.completed_evals
        else:
            avg_eval_s = 0.0

        rolling_rate_s = 0.0
        if len(self.completion_times_s) >= 2:
            span = max(1e-9, self.completion_times_s[-1] - self.completion_times_s[0])
            rolling_rate_s = (len(self.completion_times_s) - 1) / span

        concurrency_rate_s = 0.0
        if avg_eval_s > 1e-9 and busy > 0:
            concurrency_rate_s = busy / avg_eval_s

        if concurrency_rate_s > 0.0:
            throughput_eval_s = concurrency_rate_s
            throughput_mode = "concurrency_aware"
        else:
            throughput_eval_s = rolling_rate_s
            throughput_mode = "rolling_completion"

        remaining = max(0, self.total_expected_evals - self.completed_evals)
        eta_s = (remaining / throughput_eval_s) if throughput_eval_s > 1e-9 else None
        active_worker = None
        running_states = [st for st in self.worker_states.values() if st.state == "running"]
        if running_states:
            active_worker = max(running_states, key=lambda st: st.started_at).worker_id
        payload = {
            "started_at": self.started_at,
            "elapsed_s": elapsed_s,
            "simulator": self.simulator,
            "simulator_vehicle": self.simulator_vehicle,
            "simulator_world": self.simulator_world,
            "workers_total": self.worker_count,
            "workers_busy": busy,
            "workers_idle": self.worker_count - busy,
            "completed_evals": self.completed_evals,
            "failed_evals": self.failed_evals,
            "total_expected_evals": self.total_expected_evals,
            "progress_ratio": (
                self.completed_evals / self.total_expected_evals
                if self.total_expected_evals > 0
                else 0.0
            ),
            "avg_eval_s": avg_eval_s,
            "throughput_eval_per_min": throughput_eval_s * 60.0,
            "throughput_mode": throughput_mode,
            "eta_s": eta_s,
            "active_worker_id": active_worker,
            "workers": [asdict(self.worker_states[i]) for i in sorted(self.worker_states)],
        }
        atomic_write_json(self.status_file, payload)

    def start(self) -> None:
        bin_link = self.pool_dir / "bin"
        if bin_link.exists() or bin_link.is_symlink():
            if bin_link.is_symlink() and bin_link.resolve() == (self.build_dir / "bin").resolve():
                pass
            else:
                bin_link.unlink()
        if not bin_link.exists():
            bin_link.symlink_to((self.build_dir / "bin").resolve())

        self.available_workers = queue.Queue()
        cleanup_runtime_slots(
            self.repo_root,
            instance_ids=[worker.instance_id for worker in self.workers],
            ports=[worker.tcp_port for worker in self.workers],
            process_hints=[str(self.pool_dir)],
        )
        started_workers = []
        try:
            for worker in self.workers:
                worker.start()
                started_workers.append(worker)
                self.available_workers.put(worker)
        except Exception:
            for worker in started_workers:
                worker.stop()
            cleanup_runtime_slots(
                self.repo_root,
                instance_ids=[worker.instance_id for worker in self.workers],
                ports=[worker.tcp_port for worker in self.workers],
                process_hints=[str(self.pool_dir)],
            )
            raise
        with self.status_lock:
            self._write_status_locked()
        self._status_thread = threading.Thread(target=self._status_loop, name="pool-status-loop", daemon=True)
        self._status_thread.start()

    def stop(self) -> None:
        self._stop_event.set()
        if self._status_thread is not None:
            self._status_thread.join(timeout=2.0)
        for worker in self.workers:
            worker.stop()
        cleanup_runtime_slots(
            self.repo_root,
            instance_ids=[worker.instance_id for worker in self.workers],
            ports=[worker.tcp_port for worker in self.workers],
            process_hints=[str(self.pool_dir)],
        )
        with self.status_lock:
            for state in self.worker_states.values():
                state.state = "stopped"
                state.current_eval = -1
                state.current_iteration = -1
                state.phase = ""
                state.candidate = ""
                state.started_at = 0.0
            self._write_status_locked()
        self.executor.shutdown(wait=True, cancel_futures=True)

    def _status_loop(self) -> None:
        while not self._stop_event.wait(2.0):
            with self.status_lock:
                self._write_status_locked()

    def submit(self, task: EvalTask, eval_args: dict, eval_timeout_s: float, fail_penalty: float) -> Future:
        worker = self.available_workers.get()

        def run_on_worker() -> dict:
            self._set_worker_state(
                worker,
                state="running",
                current_eval=task.eval_index,
                current_iteration=task.iteration,
                phase=task.phase,
                candidate=task.candidate,
                started_at=time.time(),
                error="",
            )
            result = worker.run_eval(task, eval_args=eval_args, eval_timeout_s=eval_timeout_s, fail_penalty=fail_penalty)
            with self.status_lock:
                state = self.worker_states[worker.worker_id]
                state.state = "idle"
                state.current_eval = -1
                state.current_iteration = -1
                state.phase = ""
                state.candidate = ""
                state.started_at = 0.0
                state.last_duration_s = float(result.get("duration_s", 0.0))
                state.completed += 1
                if result.get("failed"):
                    state.failures += 1
                    state.error = str(result.get("stderr", ""))[:160]
                self._record_completion_locked(float(result.get("duration_s", 0.0)), bool(result.get("failed")))
                self._write_status_locked()
            self.available_workers.put(worker)
            return result

        future = self.executor.submit(run_on_worker)
        return future
